### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by matthiasdv** [martindurant/uavro#7]
**Issue**:

intake.open_avro_table() runs into trouble given a specific embedded avro schema. 

**Reproduce**:

Given an embedded Avro schema that contains fields like this:

```
{
    "name" : "some_field",
    "type" : [ "double", "null" ]
  },
```

calling intake.open_avro_table()  on this file produces the following log: 

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    dataframe = source.read()
  File "venv/lib/python3.7/site-packages/intake_avro/source.py", line 60, in read
    self._get_schema()
  File "venv/lib/python3.7/site-packages/intake_avro/source.py", line 41, in _get_schema
    storage_options=self._storage_options)
  File "venv/lib/python3.7/site-packages/uavro/core.py", line 289, in dask_read_avro
    head = read_header(f)
  File "venv/lib/python3.7/site-packages/uavro/core.py", line 106, in read_header
    map_types(out, val)
  File "venv/lib/python3.7/site-packages/uavro/core.py", line 77, in map_types
    t = typemap.get(entry['type'], np.dtype("O"))
TypeError: unhashable type: 'list'
```

Drilling down on this reveals that at line 77 in uavro/core.py 

https://github.com/martindurant/uavro/blob/master/uavro/core.py#L77

entry['type'] is set to [ "double", "null" ]. 

It seems the Avro schema is valid:

https://docs.oracle.com/database/nosql-12.1.3.1/GettingStartedGuide/avroschemas.html#unions

Is there a simple way to create an empty avro file and set the schema? Then I can provide a simple repository to reproduce the issue.

**Comment by martindurant** [comment]
`uavro` is meant for very strictly tabular data, i.e., a single top-level record, containing primitive types; that is what makes it fast.

> Is there a simple way to create an empty avro file and set the schema?

If memory serves - and it has been a long time since I've looked at this code - then there are utility functions along those lines used in this package for testing.

**Comment by matthiasdv** [comment]
Then I'm assuming the `open_avro_table` method on Intake would be the one to use formore complex data, as per the docs:

https://intake-avro.readthedocs.io/en/latest/quickstart.html#usage

**Comment by martindurant** [comment]
The other way around: _table for the fast, simple schema (makes a dataframe), and _sequence for the slower iterator.

**Comment by matthiasdv** [comment]
> The other way around: _table for the fast, simple schema (makes a dataframe), and _sequence for the slower iterator.

Right, mixed those up. 

Interestingly, the _sequence produces a similar error. 

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    dataframe = source.read()
  File "/venv/lib/python3.7/site-packages/intake_avro/source.py", line 132, in read
    return self._bag.compute()
  File "venv/lib/python3.7/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "venv/lib/python3.7/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "venv/lib/python3.7/site-packages/dask/multiprocessing.py", line 192, in get
    raise_exception=reraise, **kwargs)
  File "venv/lib/python3.7/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "venv/lib/python3.7/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "venv/lib/python3.7/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "venv/lib/python3.7/site-packages/dask/core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "venv/lib/python3.7/site-packages/dask/core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "venv/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "venv/lib/python3.7/site-packages/dask/bag/avro.py", line 158, in read_chunk
    return list(fastavro.iter_avro(i))
  File "fastavro/_read.pyx", line 810, in _iter_avro_records
  File "fastavro/_read.pyx", line 659, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 516, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 651, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 436, in fastavro._read.read_union
IndexError: list index out of range
```

I'm interpreting this as the fastavro package having difficulties reading the "union" data type. Probably the wrong place to ask, but do you know of an easy way to check if the .avro file and its contents are valid?

I'm at a loss trying to debug that error. Stepping through the iteration produces a few OK steps, and crashes on a certain record. The debugger is a bit cryptic as well, which i'm guessing is because fastavro is written in Cython?

**Comment by martindurant** [comment]
I'm afraid I don't know what that means, but your suggestions certainly sound reasonable. As to checking if the file is valid - I would load with fastavro (!), or try any other non-python avro framework

**Comment by matthiasdv** [comment]
Thanks for the feedback
